name: antnode

services:
  node:
    image: ghcr.io/lushdog/antnode:latest
    network_mode: 'host'
    volumes:
      - ./antnode_data:/root/antnode_data
      - ./autonom_data:/root/.local/share/autonomi
    environment:
      - REWARD_ADDRESS=${REWARD_ADDRESS}
      - NODE_COUNT=${NODE_COUNT}
    # command:
      # - "--home-network"
      # - "--upnp"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 2048m
